import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// This will be generated by build_runner
part 'app_database.g.dart';

// --- MIXIN ---
mixin SyncableTable on Table {
  TextColumn get id => text()();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();
  DateTimeColumn get clientUpdatedAt => dateTime().nullable()();
  BoolColumn get deleted => boolean().withDefault(const Constant(false))();
}

// --- TABLES ---
class Users extends Table with SyncableTable {
  TextColumn get name => text()();
  TextColumn get email => text().unique()();
  TextColumn get passwordHash => text()();
  TextColumn get role => text().withDefault(const Constant('member'))();
  @override
  Set<Column> get primaryKey => {id};
}

class Organizations extends Table with SyncableTable {
  TextColumn get name => text()();
  TextColumn get status => text().withDefault(const Constant('pending'))();
  @override
  Set<Column> get primaryKey => {id};
}

class Memberships extends Table with SyncableTable {
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get role => text()();
  TextColumn get status => text().withDefault(const Constant('pending'))();
  TextColumn get officerTitleId => text().nullable().references(OfficerTitles, #id)();
  @override
  Set<Column> get primaryKey => {id};
}

class OfficerTitles extends Table with SyncableTable {
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get title => text()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  @override
  Set<Column> get primaryKey => {id};
}

class OrganizationPermissions extends Table with SyncableTable {
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get permissionKey => text()();
  BoolColumn get enabledForOfficers => boolean().withDefault(const Constant(false))();
  @override
  Set<Column> get primaryKey => {id};
}

class MemberPermissions extends Table with SyncableTable {
  TextColumn get membershipId => text().references(Memberships, #id)();
  TextColumn get permissionKey => text()();
  BoolColumn get isGranted => boolean()();
  @override
  Set<Column> get primaryKey => {id};
}

class Events extends Table with SyncableTable {
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get name => text()();
  TextColumn get description => text().nullable()();
  DateTimeColumn get eventDate => dateTime()();
  TextColumn get location => text()();
  IntColumn get maxAttendees => integer().nullable()();
  TextColumn get createdBy => text().references(Users, #id)();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  @override
  Set<Column> get primaryKey => {id};
}

class Attendance extends Table with SyncableTable {
  TextColumn get eventId => text().references(Events, #id)();
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get studentNumber => text()();
  TextColumn get lastName => text()();
  TextColumn get firstName => text()();
  TextColumn get program => text()();
  IntColumn get yearLevel => integer()();
  DateTimeColumn get timestamp => dateTime()();
  TextColumn get status => text().withDefault(const Constant('present'))();
  @override
  Set<Column> get primaryKey => {id};
}

class UserProfiles extends Table with SyncableTable {
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get googleId => text().unique().nullable()();
  TextColumn get studentNumber => text().nullable()();
  TextColumn get firstName => text().nullable()();
  TextColumn get lastName => text().nullable()();
  TextColumn get fullName => text().nullable()();
  TextColumn get program => text().nullable()();
  IntColumn get yearLevel => integer().nullable()();
  TextColumn get section => text().nullable()();
  BoolColumn get isComplete => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
  @override
  Set<Column> get primaryKey => {id};
}

// --- DATABASE CLASS ---
@DriftDatabase(tables: [
  Users,
  Organizations,
  Memberships,
  OfficerTitles,
  OrganizationPermissions,
  MemberPermissions,
  Events,
  Attendance,
  UserProfiles,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  // Constructor for testing with in-memory database
  AppDatabase.forTesting(super.e);

  @override
  int get schemaVersion => 6;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // Migration from version 1 to 2: Add passwordHash and role columns
          await m.addColumn(users, users.passwordHash);
          await m.addColumn(users, users.role);
        }
        if (from < 3) {
          // Migration from version 2 to 3: Add new tables and columns
          await m.createTable(officerTitles);
          await m.createTable(organizationPermissions);
          await m.createTable(memberPermissions);
          await m.createTable(userProfiles);
          
          // Update Events table structure
          await m.deleteTable('events');
          await m.createTable(events);
          
          // Add officerTitleId to Memberships
          await m.addColumn(memberships, memberships.officerTitleId);
        }
        if (from < 4) {
          // Migration from version 3 to 4: Update UserProfiles structure
          // Drop and recreate the table with new schema
          await m.deleteTable('user_profiles');
          await m.createTable(userProfiles);
        }
        if (from < 5) {
          // Migration from version 4 to 5: Enhanced UserProfiles for Google Auth
          // Drop and recreate with new fields
          await m.deleteTable('user_profiles');
          await m.createTable(userProfiles);
        }
        if (from < 6) {
          // Migration from version 5 to 6: Enhanced Attendance with student details
          await m.deleteTable('attendance');
          await m.createTable(attendance);
        }
      },
    );
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'cscb_offline.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
