import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// This will be generated by build_runner
part 'app_database.g.dart';

// --- MIXIN ---
mixin SyncableTable on Table {
  TextColumn get id => text()();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();
  DateTimeColumn get clientUpdatedAt => dateTime().nullable()();
  BoolColumn get deleted => boolean().withDefault(const Constant(false))();
}

// --- TABLES ---
class Users extends Table with SyncableTable {
  TextColumn get name => text()();
  TextColumn get email => text().unique()();
  TextColumn get passwordHash => text()();
  TextColumn get role => text().withDefault(const Constant('member'))();
  @override
  Set<Column> get primaryKey => {id};
}

class Organizations extends Table with SyncableTable {
  TextColumn get name => text()();
  TextColumn get status => text().withDefault(const Constant('pending'))();
  @override
  Set<Column> get primaryKey => {id};
}

class Memberships extends Table with SyncableTable {
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get role => text()();
  TextColumn get status => text().withDefault(const Constant('pending'))();
  @override
  Set<Column> get primaryKey => {id};
}

class Events extends Table with SyncableTable {
  TextColumn get orgId => text().references(Organizations, #id)();
  TextColumn get title => text()();
  DateTimeColumn get date => dateTime()();
  @override
  Set<Column> get primaryKey => {id};
}

class Attendance extends Table with SyncableTable {
  TextColumn get eventId => text().references(Events, #id)();
  TextColumn get userId => text().references(Users, #id)();
  DateTimeColumn get timestamp => dateTime()();
  TextColumn get status => text().withDefault(const Constant('present'))();
  @override
  Set<Column> get primaryKey => {id};
}

class UserProfiles extends Table with SyncableTable {
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get name => text()();
  TextColumn get program => text()();
  IntColumn get yearLevel => integer()();
  IntColumn get section => integer()();
  @override
  Set<Column> get primaryKey => {id};
}

// --- DATABASE CLASS ---
@DriftDatabase(tables: [Users, Organizations, Memberships, Events, Attendance, UserProfiles])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // Migration from version 1 to 2: Add passwordHash and role columns
          await m.addColumn(users, users.passwordHash);
          await m.addColumn(users, users.role);
        }
        if (from < 3) {
          // Migration from version 2 to 3: Add UserProfiles table
          await m.createTable(userProfiles);
        }
        if (from < 4) {
          // Migration from version 3 to 4: Update UserProfiles structure
          // Drop and recreate the table with new schema
          await m.deleteTable('user_profiles');
          await m.createTable(userProfiles);
        }
      },
    );
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'cscb_offline.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
